name: CI workflow

on:
  push:

jobs:
  build:  # job ka naam
    runs-on: ubuntu-latest  # this run on ubuntu latest (free) its github runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4   # clone code into ubuntu runner
      
      - name: Setup Docker
        uses: docker/setup-buildx-action@v4